; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
description = "пример выполнения из flash и из sram"
[env]
platform = ststm32
board = nucleo_h745zi_q
framework = cmsis
build_flags = -std=c11 -O0 -Wall -Wextra -D CORE_CM7 -DPWR_DIRECT_SMPS_SUPPLY
board_build.cmsis.startup_file = broken_path
board_build.cmsis.system_file = broken_path
monitor_speed = 115200
test_speed = 115200
test_framework = custom ; использовать test_custom_runner.py в папке test
build_type = debug
debug_init_cmds = target extended-remote $DEBUG_PORT
    $LOAD_CMDS
    $INIT_BREAK

[env:blinker_ram]
build_flags = ${env.build_flags} -DVECT_TAB_SRAM 
board_build.ldscript = $PROJECT_DIR/system/stm32h745xx_sram1_CM7.ld
build_src_filter = +<blinker/*.c>
    +<$PROJECT_DIR/system/*>

[env:blinker2]
build_src_filter = +<$PROJECT_DIR/system/*>
    +<blinker2/*.c>
board_build.ldscript = $PROJECT_DIR/system/h745cm7_slot1_flash.ld

[env:blinker2_flash2]
build_src_filter = +<$PROJECT_DIR/system/*>
    +<blinker2/*.c>
board_build.ldscript = $PROJECT_DIR/system/h745cm7_slot1_flash.ld

[env:bootloader]
build_flags = ${env.build_flags}
board_build.ldscript = $PROJECT_DIR/system/stm32h745xx_flash_CM7.ld
build_src_filter = +<bootloader/*.c>
    +<$PROJECT_DIR/system/*>